version: "3.2"

services:
  master:
    image: 127.0.0.1:5000/master
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - worker1
    volumes:
      - datasets:/sgp/datasets/
      - results:/sgp/results/
      - parameters:/sgp/parameters/
    networks:
      janusgraph-network:
        aliases:
          - '{{.Service.Name}}-{{.Task.Slot}}'

networks:
  janusgraph-network:
    driver: overlay

volumes:
  datasets:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/miladrzh/milad/sync/datasets"
  results:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/miladrzh/milad/sync/results"
  parameters:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/miladrzh/milad/sync/params"
